# Generated by Django 3.1.7 on 2021-03-08 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20210308_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='date_hired',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 18, 19, 31, 554520)),
        ),
    ]
